<?php
/**
 * Created by PhpStorm.
 * User: egretos
 * Date: 02.04.18
 * Time: 14:29
 */

namespace ESputnicService;


use yii\mail\BaseMailer;
use yii\mail\MessageInterface;

class ESputnicMailer extends BaseMailer
{
    public $api;

    public function __construct(ESputnicApi $api, array $config = [])
    {
        $this->api = $api;
        parent::__construct($config);
    }

    /**
     * @param MessageInterface $message email message instance to be sent
     * @return bool whether the message has been sent successfully
     */
    public function send($message)
    {
        return parent::send($message); // TODO: Change the autogenerated stub
    }

    /**
     * Sends the specified message.
     * This method should be implemented by child classes with the actual email sending logic.
     * @param MessageInterface $message the message to be sent
     * @return bool whether the message is sent successfully
     */
    public function sendMessage($message)
    {
        // TODO: Implement sendMessage() method.
    }
}